name: CI/CD Pipeline

# Kapan pipeline ini jalan? Saat ada push branch 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Apa saja tugas (jobs) yang harus dilakukan?
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Github meminjamkan server ubuntu gratis

    steps:
    # 1. Ambil codingan dari repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Siapkan Node.js env
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # 3. Install dependencies
    - name: Install dependencies
      run: npm Install

    # 4. Test Build Docker Image
    - name: Build Docker Image
      run: docker build -t my-helloworld-app .
